#!/bin/bash

echo "🔧 Настройка ngrok для Sumsub Webhook"
echo "======================================"
echo ""
echo "1️⃣ Зарегистрируйся: https://dashboard.ngrok.com/signup"
echo ""
echo "2️⃣ Скопируй authtoken: https://dashboard.ngrok.com/get-started/your-authtoken"
echo ""
echo "3️⃣ Вставь команду (замени YOUR_TOKEN на свой токен):"
echo ""
echo "   ngrok config add-authtoken YOUR_TOKEN"
echo ""
echo "4️⃣ Запусти ngrok:"
echo ""
echo "   ngrok http 3000"
echo ""
echo "5️⃣ Скопируй URL (например: https://abc123.ngrok-free.app)"
echo ""
echo "6️⃣ В Sumsub Dashboard (https://cockpit.sumsub.com):"
echo "   Settings → Webhooks → Add Webhook"
echo "   URL: https://YOUR-NGROK-URL.ngrok-free.app/api/kyc/webhook/sumsub"
echo "   Events: applicantReviewed, applicantPending"
echo ""
echo "7️⃣ Пройди KYC заново - webhook придёт автоматически!"
echo ""

