#!/usr/bin/expect -f

set timeout 30

cd "/Users/bogdankononenko/Работа/Development/Project/crm vasp/credentials/bcb-sandbox/key"

spawn gpg --decrypt Production_credentials.api.gpg

expect {
    "Enter passphrase:" {
        send "\r"
        exp_continue
    }
    "passphrase:" {
        send "\r"
        exp_continue
    }
    -re "passphrase" {
        send "\r"
        exp_continue
    }
    eof
}

wait

